---
- name: Ubuntu | Python | (apt) Install required system packages.
  apt: >
    pkg={{ item }}
    state=installed
    update-cache=yes
  with_items:
    
    # pyhton code analysis/testing
    - sloccount
    - pep8
    - pyflakes
    - pylint
    
  tags:
    - base
    - packages
    - provision
    - app
        
- name: Ubuntu | Python| (pip) Install required system packages.
  pip: >
    name={{ item }} 
  with_items:
    - tox
  tags:
    - base
    - packages
    - provision
    - app
