---

- name: Gather data about target box
  hosts: jenkins
  gather_facts: yes
  tasks:
    - debug: Gather Facts
    
- name: Configure target box
  hosts: jenkins
  sudo: yes
  roles:
    - { role: ubuntu }
    - { role: ansible-jenkins }
    