---

- name: Gather data about target box
  hosts: jenkins
  gather_facts: yes
  tasks:
    - debug: Gather Facts

- name: Configure target box
  hosts: jenkins
  sudo: yes
  vars:
    port: 8081
    prefix: '/build'
    email:
      smtp_host: 'mail.example.com'
      smtp_ssl: 'true'
      default_email_suffix: '@example.com'
    plugins:
      - git
      - ssh
      - violations
      - image-gallery
      - matrix-auth
      - delivery-pipeline-plugin
      - sloccount
      - role-strategy
      - parameterized-trigger
      - matrix-auth
      - gravatar
      - cobertura
      - build-token-root
      - ws-cleanup
      - email-ext
  roles:
    - { role: ubuntu }
    - { role: ansible-jenkins }
